filetype on
syntax on
colorscheme solarized
set number
"set lines=35 columns=150
set colorcolumn=90
let mapleader=" "
" Map keys
map <leader>s :source ~/.vimrc<CR>
set guifont=Source\ Code\ Pro\ Light\ 14
set hidden
set history=100
filetype indent on
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
autocmd BufWritePre * :%s/\s\+$//e
"set hlsearch
"nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>
